# WEJAPA INTERNSHIP WAVE 5 LABS (NUMPY AND PANDAS LABS)

### NUMPY LABS

In [1]:
import numpy as np # Importing the numpy library

##### abc_numpy

In [2]:
letter_array=np.array(['a','b','c','d','e','f','g','h','i','j']) # Creating numpy array of letters a-j

print("Letter Array: ",letter_array) # 

print('dtype of Letter Array: ',letter_array.dtype) # Getting the dtype of the array

print('Shape of Letter Array: ',letter_array.shape) # Getting the shape of the array

print('Size of Letter array: ',letter_array.size) # Getting the size of the array

Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
dtype of Letter Array:  <U1
Shape of Letter Array:  (10,)
Size of Letter array:  10


##### create_ndarray

In [3]:
X=np.zeros((4,4),dtype=int) # Creating a 4,4 array filled  with zeros

# Setting all elements of the first, second, third and fouth columns to 1,2,3 and 4 respectively
X[:,0],X[:,1],X[:,2],X[:,3]=1,2,3,4 


print(X)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


##### create_ndarray1

In [4]:
X1=np.arange(2,33,2).reshape(4,4,order='C') # Populating the array in the order of C
X2=np.arange(2,33,2).reshape(4,4,order='F')  # Populating the array in the order of Fortran

In [5]:
print(X1)
print('\n')
print(X2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


[[ 2 10 18 26]
 [ 4 12 20 28]
 [ 6 14 22 30]
 [ 8 16 24 32]]


##### pick_odd

In [6]:
X=np.arange(1,26).reshape(5,5) # Cresating the array and reshaping to 5,5
X=X[X%2==0] # Using boolean indexing to pick the even numbers

In [7]:
print(X)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [8]:
Y=np.arange(1,26).reshape(5,5) #creating the array and reshaping to 5,5
Y=Y[Y%2!=0] # Using boolean indexing to pick the odd numbers

In [9]:
print(Y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


### PANDAS LABS

In [10]:
import pandas as pd # Importing the required library
pd.set_option('precision',1)

##### book_r

In [11]:
# Creating Pandas Series from lists
books = pd.Series(data = ['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland' ])
authors = pd.Series(data = ['Charles Dickens', 'John Steinbeck', 'William Shakespeare', ' H. G. Wells', 'Lewis Carroll' ])

user_1 = pd.Series(data = [3.2, np.nan ,2.5])
user_2 = pd.Series(data = [5., 1.3, 4.0, 3.8])
user_3 = pd.Series(data = [2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data = [4, 3.5, 4, 5, 4.2])


In [12]:
# Creating dictionary
dat={'Author':authors,'Book Title':books,'User1':user_1,'User2':user_2,'User3':user_3,'User4':user_4}

In [13]:
# Converting dictionary into Pandas DataFrame
book_ratings=pd.DataFrame(dat)

In [14]:
book_ratings

Author           Book Title  User1  User2  User3  User4
0      Charles Dickens   Great Expectations    3.2    5.0    2.0    4.0
1       John Steinbeck      Of Mice and Men    NaN    1.3    2.3    3.5
2  William Shakespeare     Romeo and Juliet    2.5    4.0    NaN    4.0
3          H. G. Wells     The Time Machine    NaN    3.8    4.0    5.0
4        Lewis Carroll  Alice in Wonderland    NaN    NaN    NaN    4.2

In [15]:
book_ratings.fillna(book_ratings.mean(),inplace=True) # Filling the missing values  with the average rating in each column

In [16]:
book_ratings

Author           Book Title  User1  User2  User3  User4
0      Charles Dickens   Great Expectations    3.2    5.0    2.0    4.0
1       John Steinbeck      Of Mice and Men    2.9    1.3    2.3    3.5
2  William Shakespeare     Romeo and Juliet    2.5    4.0    2.8    4.0
3          H. G. Wells     The Time Machine    2.9    3.8    4.0    5.0
4        Lewis Carroll  Alice in Wonderland    2.9    3.5    2.8    4.2

##### sun_planets

In [17]:
distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6] # in units of 10^6 km
planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']

dist_planets=pd.Series(distance_from_sun,index=planets)

c=18 # in unit of 10^6 km/minute

time_light=(dist_planets)/c

close_planets=time_light[time_light<40]

In [18]:
close_planets

Earth     8.3
Mars     12.7
Venus     6.0
dtype: float64